### ISSUE TITLE
Adapter throws " ls: Zugriff auf '/dev/disk/by-id/' nicht möglich: Datei oder Verzeichnis nicht gefunden" in Docker

### ISSUE THREAD

**Issue by buanet** [iobroker-community-adapters/ioBroker.info#230] opened 2021-02-07 13:01 UTC
**Describe the bug**  
On startup the adapter throws a `ls: Zugriff auf '/dev/disk/by-id/' nicht möglich: Datei oder Verzeichnis nicht gefunden` error message in container log when running inside a docker container where "/dev/disk" not exists.
The error is only shown in container log. No error in ioBroker log.

**To Reproduce**  
1. Start any new docker container based on "buanet/iobroker:latest"
2. See error in container log when ioBroker (and it adapters) start

**Expected behavior**  
Adapter detects running in a docker container and skips the step which results in that error.

**Screenshots & Logfiles**  
container log from startup:
```
================================== > LOG REDIRECT system.adapter.admin.0 => true [starting],
host.iobrokertest check instance "system.adapter.admin.0" for host "iobrokertest",
host.iobrokertest check instance "system.adapter.discovery.0" for host "iobrokertest",
host.iobrokertest check instance "system.adapter.info.0" for host "iobrokertest",
================================== > LOG REDIRECT system.adapter.admin.0 => false [Process stopped],
================================== > LOG REDIRECT system.adapter.admin.0 => false [system.adapter.admin.0.logging],
ls: Zugriff auf '/dev/disk/by-id/' nicht möglich: Datei oder Verzeichnis nicht gefunden
```

**Versions:**  
 - Adapter version: 1.7.15
 - JS-Controller version: 3.2.7
 - Node version: v12.20.1
 - Operating system: official Docker image bases on Debian Buster ;)

Regards,
André

**Comment by winnyschuster** [comment] 2021-02-10 17:39
this error is caused by npm package `systeminformation`, i have opened [an issue there](https://github.com/sebhildebrandt/systeminformation/issues/485)

**Comment by winnyschuster** [comment] 2021-02-11 01:09
developer now fixed this issue in version 5.2.1. Installing in iobroker fixed the issue here. i also have not seen any abnormalities in iobroker after the install.

**Comment by meAThomeDOTcom** [comment] 2021-02-28 09:55
Hi All, I also run into this problem just now with iobroker docker from scratch installation following the buanet guide.
The docker is not booting enough to connect with the console and patch anything inside.
Unfortunately I don’t have the skills yet to patch and build a fixed version into an own docker.
So my question/ask is after this very fast fix of the systeminformation npm if we can get soon a new stable version of iobroker.info using this fixed sysinfo npm?
Many thanks in advance for your help!
I‘m looking forward to play around, grow my automation experience and use iobroker as my home central soon.
/me

**Comment by Stoj** [comment] 2021-02-28 11:51
Hallo alle zusammen.
habe bei der Installation von ioBroker auf Docker den gleichen fehler und weis nicht mehr weiter und hoffe auf Hilfe.
Installiert habe ich es auf QNAP TS251+ Container Station die aktuelle Version von buanet/ioBroker.
Meine Englischkenntnisse sind nicht so besonders.

im vorraus Danke

**Comment by Stoj** [comment] 2021-02-28 11:55
Hier ist das Installationslog


-----   Step 2 of 5: Detecting ioBroker installation   -----                                                                                                                                                                                                
------------------------------------------------------------                                                                                                                                                                                                
                                                                                                                                                                                                                                                            
Existing installation of ioBroker detected in /opt/iobroker.                                                                                                                                                                                                
                                                                                                                                                                                                                                                            
------------------------------------------------------------                                                                                                                                                                                                
-----   Step 3 of 5: Checking ioBroker installation    -----                                                                                                                                                                                                
------------------------------------------------------------                                                                                                                                                                                                
                                                                                                                                                                                                                                                            
(Re)Setting folder permissions (This might take a while! Please be patient!)...                                                                                                                                                                             
Done.                                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                            
Fixing "sudo-bug" by replacing sudo in iobroker with gosu...                                                                                                                                                                                                
Done.                                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                            
------------------------------------------------------------                                                                                                                                                                                                
-----      Step 4 of 5: Applying special settings      -----                                                                                                                                                                                                
------------------------------------------------------------                                                                                                                                                                                                
                                                                                                                                                                                                                                                            
Some adapters have special requirements/ settings which can be activated by the use of environment variables.                                                                                                                                               
For more information take a look at readme.md on Github!                                                                                                                                                                                                    
                                                                                                                                                                                                                                                            
------------------------------------------------------------                                                                                                                                                                                                
-----          Step 5 of 5: ioBroker startup           -----                                                                                                                                                                                                
------------------------------------------------------------                                                                                                                                                                                                
                                                                                                                                                                                                                                                            
Starting ioBroker...                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                            
host.ioBroker check instance "system.adapter.admin.0" for host "ioBroker"                                                                                                                                                                                   
host.ioBroker check instance "system.adapter.discovery.0" for host "ioBroker"                                                                                                                                                                               
host.ioBroker check instance "system.adapter.info.0" for host "ioBroker"                                                                                                                                                                                    
ls: Zugriff auf '/dev/disk/by-id/' nicht möglich: Datei oder Verzeichnis nicht gefunden                                                                                                                                                                     
                                                                                                                                                                                                                                                            
ls: Zugriff auf '/dev/disk/by-id/' nicht möglich: Datei oder Verzeichnis nicht gefunden

**Comment by Surfer2010** [comment] 2021-02-28 14:21
Version v5.0.0 works, so you might have to go back to that as "latest" ?!

**Comment by buanet** [comment] 2021-02-28 15:20
Nochmal, wie [hier](https://github.com/buanet/ioBroker.docker/issues/166#issuecomment-774671587) schon erwähnt.
Dieser Fehler
```
ls: Zugriff auf '/dev/disk/by-id/' nicht möglich: Datei oder Verzeichnis nicht gefunden
ls: Zugriff auf '/dev/disk/by-id/' nicht möglich: Datei oder Verzeichnis nicht gefunden
```
hat keinerlei Auswirkungen auf die Funktion des ioBrokers!!! Ihr könnt ihn einfach ignorieren oder den info adapter deinstallieren. ;) Nichts desto trotz sollte dieser Bug natürlich am Besten in einer der nächsten Versionen des info Adapters behoben werden.  
Seitens der verwendeten Library ist der Fehler bereits gefixt ([siehe hier](https://github.com/iobroker-community-adapters/ioBroker.info/issues/230#issuecomment-776888223)).

MfG,
André

**Comment by Stoj** [comment] 2021-02-28 15:33
Hallo Andre,
danke für die Info. Ich habe dennoch keinen zugriff auf ioBroker.
Wie kann ich jetzt darauf zugreifen ?

**Comment by meAThomeDOTcom** [comment] 2021-02-28 16:33
Many thanks for your answer André!
It was late last night when I tried the docker installation and I would say too late for realizing that ioBroker itself was accessable already over the web interface. 🤦🏻‍♂️
I just expected the Starting ioBroker done... to show up before considering the service to be alive and as I also couldn’t get portainer connecting to the console I jumped to the conclution the complete installatiion broke. 
Sorry for the inconveniance!
Again many thanks for your help and for the ioBroker as docker in general!
/me

**Comment by Stoj** [comment] 2021-03-01 05:53
![image](https://user-images.githubusercontent.com/7680921/109457167-99bedd80-7a5a-11eb-875a-df4bc9856323.png)

So schaut es aus. Merkwürdig das der ioBroker keine URL zuweist.

Hat jemand eine Idee?

**Comment by buanet** [comment] 2021-03-01 22:18
@meAThomeDOTcom 

> I just expected the Starting ioBroker done... 

Ya, it's not the first time I get this answer. :) Looks like there ist some potential to optimize the logging output. 
At the moment the startup script is designed to show the Log of the ioBroker after the iobroker start call... Maybe I can add an additional hint or something... Thanks for the feedback.   

@Stoj 
Dein Log ist abgeschnitten (Startet bei Schritt 2), ich kenne dein Setup nicht und die gute Container Station habe ich mangels QNAP Hardware bisher nur auf Screenshots gesehen. Schau doch am besten mal mit ein paar mehr Infos und dem kompletten Log im [ioBroker Forum Thread zum Docker Container](https://forum.iobroker.net/topic/4733/howto-iobroker-unter-docker-auf-synology-diskstation) vorbei. Dann schauen wir uns die Sache mal an. 

MfG,
André

**Comment by Stoj** [comment] 2021-03-05 05:59
Hallo alle zusammen,
@andre Danke dir für deinen Tipp mein Probleme hier nochmal zu schildern und hoffe auf Hilfe weil ich seit Wochen mich damit rumärgere und keinen Millimeter voran komme. Da ich in dem anderen Forum keine Antworten bekomme habe ich das Thema hier noch einmal gepostet. Hoffe das es in Ordnung ist.

Ich habe ein QNAP TS251+ und wollte in die Container Station nach Anleitung ioBroker Installieren. Die Installation verlief einwandfrei aber es wird ihm keine URL zugeordnet und ich habe keinen Zugriff darauf (warum auch immer).

**_Hier einmal den Log ab Step 2_**

----- Step 2 of 5: Detecting ioBroker installation -----
Existing installation of ioBroker detected in /opt/iobroker.

----- Step 3 of 5: Checking ioBroker installation -----
(Re)Setting folder permissions (This might take a while! Please be patient!)...
Done.

Fixing "sudo-bug" by replacing sudo in iobroker with gosu...
Done.

----- Step 4 of 5: Applying special settings -----
Some adapters have special requirements/ settings which can be activated by the use of environment variables.
For more information take a look at readme.md on Github!

----- Step 5 of 5: ioBroker startup -----
Starting ioBroker...

host.NAS025F38 check instance "system.adapter.admin.0" for host "NAS025F38"
host.NAS025F38 check instance "system.adapter.discovery.0" for host "NAS025F38"
host.NAS025F38 check instance "system.adapter.info.0" for host "NAS025F38"
ls: Zugriff auf '/dev/disk/by-id/' nicht möglich: Datei oder Verzeichnis nicht gefunden

ls: Zugriff auf '/dev/disk/by-id/' nicht möglich: Datei oder Verzeichnis nicht gefunden

**_Log ende_**

Hier noch einige Screenshots von den Einstellungen

https://forum.iobroker.net/assets/uploads/files/1614754967393-2cb7e8a5-5c8b-4b45-aa99-da76fae606c9-image.png

https://forum.iobroker.net/assets/uploads/files/1614755003243-69485713-3b7e-4c20-91a6-3fe5a771f73d-image.png

Euch allen schon einmal Danke für eure Hilfe und ich freue mich schon auf eure Tipps und Hilfe

MfG Stoj

**Comment by buanet** [comment] 2021-03-05 10:38
@Stoj 
So leid es mir tut, dies ist nicht der richtige Platz für dein Problem.
Die issues auf Github sind kein Supportforum. 

MfG,
André

**Comment by buanet** [comment] 2021-03-28 15:31
@ldittmar81 @Apollon77 
Hi, can someone please check if it is possible to update dependency "systeminformation" to at least v5.2.1?

The error message is the last entry when you start a new docker container. So some users open issues or asking for support when they see the error message and cannot access the admin in their first attempt, not knowing that the error message has definitely no impact to ioB. :)

Thank you. Regards,
André

**Comment by Apollon77** [comment] 2021-03-28 15:33
Sure. I do tonight or tomorrow

**Comment by ldittmar81** [comment] 2021-03-28 20:34
Show here for changes from 4.x to 5.x https://systeminformation.io/changes.html

**Comment by JockelBln** [comment] 2021-05-06 08:45
Wenn ich die Einstellungen für den Info-Adapter unter Instanzen ändere und anschließend speichere, erscheint im Container Log übrigens die Meldung auch.

**Comment by buanet** [comment] 2021-05-06 09:09
@JockelBln Jop, die kommt jedes mal wenn der Adapter gestartet wird. Da der Adapter neu startet wenn man Einstellungen speichert, kommt die Meldung auch dann... :)

@Apollon77 Hattest du mal einen Blick auf die dependency "systeminformation" geworfen?

MfG,
André

**Comment by JockelBln** [comment] 2021-05-06 09:22
Ahh, danke für den Hinweis!
Ich bin halt schon älteres Semester und arbeite mich gerade erst in die Materie ein.

**Comment by Apollon77** [comment] 2021-08-04 19:00
plese try latest info version

**Closed by Apollon77** 2021-08-04 19:00 UTC
Labels: wontfix
