### ISSUE TITLE
Annoying note

### ISSUE THREAD

**Issue by rocklobster42195** [iobroker-community-adapters/ioBroker.info#51] opened 2019-08-06 09:43 UTC
The note "Die Entwicklung geht weiter..." is really annoying and constantly pops up.
Best regards
Boris

**Comment by ldittmar81** [comment] 2019-08-26 16:52
I know... sorry... it is a cache problem or so. I'm not sure where the problem is. The message should only be displayed once. :(

**Comment by ldittmar81** [comment] 2019-08-29 09:11
https://github.com/ioBroker/ioBroker.admin/pull/421

First try

**Comment by ldittmar81** [comment] 2019-09-27 05:53
Fixed with ioBroker admin 3.6.5

**Closed by ldittmar81** 2019-09-27 05:53 UTC
Labels: bug, help wanted
